### ISSUE TITLE
PartKeepr integration?

### ISSUE THREAD

**Issue by timofonic** [xesscorp/KiCost#23]
Hello

Are there a possibility to make this project integrated with PartKeepr? 
As your project is a specific KiCad solution, maybe you can be interested on it or ask for a bounty for that. 

I asked both projects, but no luck.

https://github.com/partkeepr/PartKeepr/issues/524
https://github.com/KiCad/kicad-library/issues/342

I need it for accessibility reasons. More details later on the online project page/log :)

Kind regards.

**Comment by xesscorp** [comment]
How do you envision KiCost working with PartKeepr? I can see KiCost pulling in the available quantity in inventory for each part in a schematic from PartKeepr, but I don't know what else it would do.
