### ISSUE TITLE
Http escape characters in part numbers

### ISSUE THREAD

**Issue by anderwm** [xesscorp/KiCost#341]
Request can fail or completely, or return the wrong part number if the "query" variable contains a url escape character. '#' is the one that got me, but likely there are others.

**Comment by hildogjr** [comment]
Please, attach some CSV/XML BoM to help us to reproduce.

**Comment by anderwm** [comment]
I think anything with a part number like 'LTC4364HS-2#PBF' should be sufficient. If you can't recreate it I will redact a BOM for you so that I can post it. It seems to solve the problem if you do the request like 

>  url = 'http://octopart.com/api/v3/parts/match'
payload = (('queries',json.dumps(query)),('apikey','xxx'),('include[]','specs'),('include[]','datasheets'))
response = requests.get(url, params=payload)`

instead

**Comment by hildogjr** [comment]
I just create a CSV BoM (just placing 'LTC4364HS-2#PBF' inside) for reproduce. Results:

I was not able to get any result with the current code or your when I look for '1n4148'.

The part 'LTC4364HS-2#PBF' results in a 400 error (bad request). The reason may by the interpretation of '#" that have to be passed as '%xx' (`urllib` may provide the function for the correct conversion).
